### ISSUE TITLE
Bug: Super Smash Bros. Freezes after pressing Start Button During Intro Sequence in Glide64

### ISSUE THREAD

**Issue by AkiraTak97** [Rosalie241/RMG#101] opened 2023-02-13 05:10 UTC
When using the Glide64 Graphics Plugin, After the Nintendo and HAL Laboratory logo appear on the screen during the intro, whenever the Start button is pressed, the screen freezes and the audio plays back slowly. The only remedy thus far is to wait for the intro in its entirety to play back, or switch to the ParaLLEI plugins. Please consider looking into this soon.

**Comment by Rosalie241** [comment] 2023-02-13 19:13
I'm unable to reproduce this, it works fine for me when playing the intro with GLideN64, no slowdowns or such at all.

**Comment by AkiraTak97** [comment] 2023-02-13 20:07
I'm using Windows 10.
My build has an Intel Core i5 7300HQ with NVIDIA GT 1050 4GB.
Video Plugin is GlideN64 rev.698f5580.
Audio and Input Plugins are Rosalie's Mupen GUI
RSP Plugin id Hacktarux/Azimer.
In Settings for Super Smash Bros., Memory size is 8 MB, Save Type SRAM, Counter Factor 1, and SI DMA Duration is 2304.
Randomize PI/SI Interrupt Timing is Enabled, as is Override Core Settings. CPU Emulator is Dynamic Recompiler.

**Comment by AkiraTak97** [comment] 2023-02-13 20:08
The slowdown happens when pressing Start during the intro.

**Comment by RadikAlice** [comment] 2023-02-13 21:04
> I'm using Windows 10. My build has an Intel Core i5 7300HQ with NVIDIA GT 1050 4GB. Video Plugin is GlideN64 rev.698f5580. Audio and Input Plugins are Rosalie's Mupen GUI RSP Plugin id Hacktarux/Azimer. In Settings for Super Smash Bros., Memory size is 8 MB, Save Type SRAM, Counter Factor 1, and SI DMA Duration is 2304. Randomize PI/SI Interrupt Timing is Enabled, as is Override Core Settings. CPU Emulator is Dynamic Recompiler.

Basically stock. How odd, can't reproduce it either. But the funny thing is, I remember something like you describe
happening to me in the mid 00s with my mid to low end PC when using Project64 1.6

**Comment by AkiraTak97** [comment] 2023-02-13 21:17
Hey...I think it works now. When booting it up the first time without playing through the intro, the intro would freeze after pressing start.

**Comment by Rosalie241** [comment] 2023-02-14 20:40
Considering you can't reproduce it anymore, I'll close this issue.

I'd like to mention it could've been shader compilation stutter too, and those get cached, which'd match your issue's symptoms!

**Closed by Rosalie241** 2023-02-14 20:40 UTC
