### ISSUE TITLE
Upside Down

### ISSUE THREAD

**Issue by sleepiestsheepiest** [Rosalie241/RMG#136] opened 2023-05-18 21:05 UTC
Okay, this is a bug that I've only seen on mobile emulators, but it seems to happen to me under odd circumstances.
I am trying to emulate Mario Party 3 for my friends (We like watching the computers fight) and when I attempted to stream the game directly to my friends over discord, the screen would either flicker rapidly to be upside down or right side up, or be stuck upside down. Other than that, no issues seem to occur when playing the game

I should note that if I share my whole screen, and not just try to share the game window, it's perfectly fine too. It's only when I share the game screen to my friends that this bug occurs. I apologize too if this has been answered before, I'm not exactly the savviest with these emulators in general.

EDIT: On discord's preview it looks okay, I'm just wondering now why the emulator itself wigs out when someone streams to it.

**Comment by Rosalie241** [comment] 2023-06-01 20:42
I'm not sure what the issue is and I cannot do anything about it sadly, so closing.

**Closed by Rosalie241** 2023-06-01 20:42 UTC
