### ISSUE TITLE
Issues with command line startup zip archives with East Asian filenames

### ISSUE THREAD

**Issue by crashGG** [Rosalie241/RMG#87] opened 2023-01-20 15:31 UTC
Platform / OS : win10 x64

Github hash: newest

Issue:
Start the zip with East Asian filenames at the command line, it doesn't work.for example:
RMG.exe "罪与罚.zip"

show this error:
<img width="176" alt="2023-01-20_182154" src="https://user-images.githubusercontent.com/80488411/213735795-588f285e-522a-4164-beb6-fb4d737d7259.png">

but start the .z64 with East Asian filenames at the command line, it works fine.for example:
RMG.exe "罪与罚.z64"

**Comment by Rosalie241** [comment] 2023-01-20 16:34
This is a limitation of
1) the win32 `char` type (it only supports ANSI, while `wchar_t` would support UTF-8), i.e linux is sane in this regard and supports UTF-8 in `char`
2) minizip, the library I use to extract zip archives, due to it not exposing an API to open a filename using `wchar_t`

I'm not planning to switch to a different zip extraction library anytime soon but it should work fine on i.e linux.

**Comment by Rosalie241** [comment] 2023-01-21 13:08
Actually, after re-reading the documentation, I think I can fix this issue!

**Comment by Rosalie241** [comment] 2023-01-21 14:41
I've resolved the issue and cannot reproduce it locally anymore, can you try https://github.com/Rosalie241/RMG/actions/runs/3975236435 to see if it's been fixed for you aswell? :heart:

**Comment by crashGG** [comment] 2023-01-21 18:24
yes , it has been fixed. test with [g3c0698d](https://github.com/Rosalie241/RMG/suites/10504064993/artifacts/521280517)

**Comment by Rosalie241** [comment] 2023-01-22 02:08
Thank you, the fix will be included in the next release then!

Thanks for reporting & testing, and I apologize for my initial reaction :heart:

**Comment by crashGG** [comment] 2023-01-22 06:32
> Thank you, the fix will be included in the next release then!
> 
> Thanks for reporting & testing, and I apologize for my initial reaction ❤️

RMG is the best N64 emulator, and you are the best.

**Comment by Rosalie241** [comment] 2023-01-23 21:59
The fix has been included in v0.3.0, thanks for the report! :heart:

**Closed by Rosalie241** 2023-01-23 21:59 UTC
