### ISSUE TITLE
The settings of Angrylion RDP Plus doesn't function/do anything in v0.2.5 of RMG

### ISSUE THREAD

**Issue by RokkumanX** [Rosalie241/RMG#73] opened 2022-12-18 07:31 UTC
Hello Rosalie!

I'm really loving RMG to it's fullest but I have stumbled upon a weird bug where I'm unable to change settings with Angrylion RDP Plus in RMG v0.2.5
Well technically you can change settings but they don't get applied at all, they are saved however as they match the ones in the mupen64plus.cfg file but they do nothing.

If I were to exchange the Angrylion RDP Plus plugin from RMG v0.2.5 with an older one from let's say RMG v0.1.9 (which is the oldest one I got) all my saved settings from the GUI/mupen64plus.cfg works immediately but the only caveat is that you are no longer able to customize the settings from the UI but only through tweaking the mupen64plus.cfg file.

Also as a side-note, ParaLLEl is totally unaffected by any of this. Everything works as intended as far as changing settings go in both GUI and mupen64plus.cfg.

A very big thank you in advance! ❤️

**Comment by GhostlyDark** [comment] 2022-12-18 18:19
Can't reproduce this using RMG v0.2.5. It loads and saves settings and Angrylion-Plus respects those settings just fine (Win10).
What operating system are you using?

**Comment by RokkumanX** [comment] 2022-12-18 20:08
I'm using Windows 10 Enterprise LTSB 21H2.

Yes it loads and saves the settings but the image quality doesn't change, it seems to always output Filtered + Hybrid even if I change it to Unfiltered + Bilinear which I always use.

If I set it to Depth you would notice the difference immediately, that's why the Angrylion RDP Plus plugin from v0.1.9 works the way it should.

This is how it works for me:

1. I use the v0.2.5 package plugin
2. I change the default Filtered + Hybrid to Unfiltered + Bilinear from either the GUI or the mupen64plus.cfg
3. I restart the emulator, load a game and nothing have changed image wise, still Filtered + Hybrid quality despite the change
4. I exchange the v0.2.5 plugin with the 0.1.9 plugin and the image outputs proper Unfiltered + Bilinear image quality

Not much else to say about it really, but if no one else have the same problem I can live with using the v0.1.9 plugin and change settings manually in the mupen64plus.cfg

**Comment by GhostlyDark** [comment] 2022-12-18 20:26
I see. I made some mistakes introducing the GUI. I pointed it out to Rosalie, so it should get fixed soonish.
https://github.com/Rosalie241/angrylion-rdp-plus/blob/RMG/src/plugin/mupen64plus/gfx_m64p.cpp#L212-L218

**Comment by RokkumanX** [comment] 2022-12-19 03:19
Thank you very much, looking forward to the fix!

**Comment by Rosalie241** [comment] 2022-12-20 11:30
I've fixed it, will be included in the next release, but sadly that'll take a little while due to a UI overhaul I'm working on

**Comment by RokkumanX** [comment] 2022-12-20 15:19
Anything you are working on is worth the wait, keep shining!

**Comment by Rosalie241** [comment] 2022-12-28 00:00
Fixed in v0.2.6! :two_hearts:

**Closed by Rosalie241** 2022-12-28 00:00 UTC

**Comment by RokkumanX** [comment] 2022-12-29 13:55
Thanks Rosalie, it works great now!
