### ISSUE TITLE
[Issue] Crash when shutting down and starting a new game when using Parallel video plugin

### ISSUE THREAD

**Issue by vini1264** [Rosalie241/RMG#177] opened 2023-09-19 22:11 UTC
Hello, in version 0.5.2 of RMG there's an issue when the Parallel video plugin is selected, which is when I shut down a game and start another one the emulator ends up crashing.

**Comment by Flax4** [comment] 2024-01-04 21:26
Can confirm this. 

Version 0.5.4
Windows 11 23H2

**Comment by ManGuyNY** [comment] 2024-03-14 04:34
Still present on v0.5.7 on Windows 11. Not sure if there is any log file I can provide, but it's very easily reproducible by just opening and closing a ROM twice using the Parallel plugins.

**Comment by Rosalie241** [comment] 2024-06-03 13:21
I've taken a look and attempted to fix the issue, can any of you please try the following build to see if that fixes it for you?

https://github.com/Rosalie241/RMG/actions/runs/9350935443

**Comment by vini1264** [comment] 2024-06-03 15:05
> I've taken a look and attempted to fix the issue, can any of you please try the following build to see if that fixes it for you?
> 
> https://github.com/Rosalie241/RMG/actions/runs/9350935443
Unfortunatelly there's now another issue with the Parallel plugin in this build, when I play a game in fullscreen and keep playing for a while the screen glitches out and stops working, shutting down and trying to re-open the game after facing this issue gives me this error message

![2024-06-03 105636](https://github.com/Rosalie241/RMG/assets/52476409/af0ea8b9-e75d-4c5c-90d4-f48da3e1d0bf)

**Comment by vini1264** [comment] 2024-06-03 15:16
Here's a recording of the issue

https://github.com/Rosalie241/RMG/assets/52476409/d0410086-da61-4cf6-8f0d-a5260656b50f

**Comment by Rosalie241** [comment] 2024-06-03 19:24
Can you look at view -> log when that happens?

**Comment by vini1264** [comment] 2024-06-03 19:37
Here's what the log is saying

![image](https://github.com/Rosalie241/RMG/assets/52476409/ff086cf6-e37d-49f1-89c8-befc589896cc)

**Comment by Rosalie241** [comment] 2024-06-03 21:09
From a quick search online, that might be a graphics driver bug, can you try updating your graphics driver if possible?

**Comment by vini1264** [comment] 2024-06-03 21:20
> From a quick search online, that might be a graphics driver bug, can you try updating your graphics driver if possible?

I'm already on the latest version of Nvidia's drivers, my GPU is a GTX 1060 btw

**Comment by Rosalie241** [comment] 2024-06-04 06:50
hmm! Personally I have an AMD gpu and it works fine for me,

Can you try simple64 to see if the same happens there? It also uses parallel and also uses vulkan natively like RMG, so it'd be interesting to know whether it reproduces there aswell.

**Comment by Rosalie241** [comment] 2024-06-05 21:50
I've included the fix for the crash in v0.6.1 (with some minor changes)

**Comment by ManGuyNY** [comment] 2024-06-06 12:12
> I've taken a look and attempted to fix the issue, can any of you please try the following build to see if that fixes it for you?
> 
> https://github.com/Rosalie241/RMG/actions/runs/9350935443

Can confirm the original issue has been resolved for me after updating to v0.6.1

Thanks for the fix!

**Comment by Rosalie241** [comment] 2024-06-06 19:49
Thank you for reporting back aswell, I apologize it took so long to fix though!

I'll close this issue because the issue has been fixed and @vini1264 I'd recommend you open a seperate issue when you've tried it in simple64 aswell (or you can try to copy the parallel plugin from v0.6.0 to a v0.6.1 install to see if that works, there are some issues with the updated parallel that the dev of parallel is looking into)

**Closed by Rosalie241** 2024-06-06 19:49 UTC
