### ISSUE TITLE
Can't get Fullscreen to work (57b7811)

### ISSUE THREAD

**Issue by RokkumanX** [Rosalie241/RMG#19] opened 2021-10-27 07:05 UTC
**Describe the bug**
I'm trying to fullscreen with Alt+Enter but it won't respond to my input, it doesn't go fullscreen either if I click on the menu item in the GUI and then I have to force close by using Task Manager because RMG is not responding.

Also if I press Alt+Enter RMG stops responding after a while but I can still hear the game so I have to force close once again in Task Manager.

**To Reproduce**
1. Start/load a game from the GUI
2. Attempt using Alt+Enter to fullscreen or click Fullscreen in the GUI
3. Nothing happens and the application stops responding/hangs

**Expected behavior**
Be able to go fullscreen without hanging.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 Enterprise 21H1
 - GPU: NVIDIA GTX 1070
 - RAM: 64GB

**Additional context**
Using ParaLLEl RSP and ParaLLEl RDP, also using cxd4 SSE2 RSP with angrylion RDP Plus with RMG (57b7811)

**Comment by Rosalie241** [comment] 2021-10-29 18:13
I can indeed reproduce the hang with angrylion-rdp-plus but not with ParaLLeL, will investigate soon.

**Comment by RokkumanX** [comment] 2021-10-30 06:42
I'm sorry, I got a little carried away, it should only be angrylion-rdp-plus that causes the hang now.
My bad...

The specific version that I shipped with the .zip file is from m64p's last angrylion-rdp-plus package this summer which is based of the Angrylion RDP Plus v1.6 release from january 3rd.

Anyway I just saw that the plugin have been updated by the original author ata4 so here is the latest plugin from 2021-10-26

[mupen64plus-video-angrylion-plus.zip](https://github.com/Rosalie241/RMG/files/7445967/mupen64plus-video-angrylion-plus.zip)

Really hope it would be helping you!

**Comment by Rosalie241** [comment] 2021-10-31 12:52
I took a look at it and see the problem, it'll take a little while to fix though because I'm busy with a big backend overhaul (see https://github.com/Rosalie241/RMG/tree/RMG-Core ) which currently has the biggest priority for RMG :heart:

**Comment by RokkumanX** [comment] 2021-10-31 13:03
No problem at all Rosalie, everything being worked on with RMG is worth waiting for!

Keep up the great work :)

**Comment by Rosalie241** [comment] 2021-12-23 14:07
should be fixed in the latest release :heart:: https://github.com/Rosalie241/RMG/releases/latest

**Closed by Rosalie241** 2021-12-23 14:07 UTC

**Comment by RokkumanX** [comment] 2021-12-27 12:50
Thank you very much Rosalie, I see you have been very busy!

Can't wait to try this out later this week.

**Comment by RokkumanX** [comment] 2021-12-28 08:56
Everything worked beautifully ❤️

You have done a fantastic work and it's really starting to show!

**Comment by Rosalie241** [comment] 2021-12-28 09:23
Thank you :heart:
