### ISSUE TITLE
Xbox Gamepad Bumpers Glitchy

### ISSUE THREAD

**Issue by Lisoph** [Rosalie241/RMG#82] opened 2023-01-12 00:02 UTC
The bumpers of an Xbox gamepad don't seem to map cleanly to any button on the N64 controller using `Rosalie's Muepn GUI - Input Plugin`. It doesn't matter which N64 button they're bound to, they behave the same. It's unclear whether this occurs with any Xbox controller, or just my specific model (Xbox Elite Wireless Controller Series 2). It doesn't matter whether the gamepad is connected over wire or wireless, the same exact glitchy behavior occurs.

[Gamepad.webm](https://user-images.githubusercontent.com/3426722/211942728-1d6ee5fe-1eba-49c2-9361-0bc63ec05995.webm)

Gamepad testing site used: [here](https://gamepad-tester.com/).

Tested with RMG v0.2.9.

**Comment by Rosalie241** [comment] 2023-01-12 00:13
The configuration GUI uses a different way of polling inputs than the actual input plugin code, that 'sticky' issue is known but I can't do anything about it as far as I know, I'll investigate it (and perhaps rework the code) more in the future (as I'm sick now), in-game it should behave fine however.

**Comment by Lisoph** [comment] 2023-01-12 01:02
@Rosalie241 thanks for the swift reply! Yeah it's indeed working fine in-game. Browsing the code I had my suspicions that there were some polling shenanigans going on. Maybe adding a label, stating something like "sticky analog behavior is only visual", could be a good idea? The actual fix would probably require a lot of code to change.

Take your time, get well soon!

**Comment by Rosalie241** [comment] 2023-02-05 12:32
Can you try this build: https://github.com/Rosalie241/RMG/actions/runs/4096583401 and see if that fixes it for you?

**Comment by Rosalie241** [comment] 2023-02-06 21:54
Hopefully fixed in v0.3.2, please do re-open this issue if it still exists, Im unable to reproduce it now though!

**Closed by Rosalie241** 2023-02-06 21:54 UTC
